/** A single `@font-face` we ship, generated by scripts/fetch-fonts.mjs. */
export interface FontFace {
  /** Font id, matches `FontOption.id`. */
  id: string
  /** CSS font-family name as served by Google Fonts. */
  family: string
  /** Path inside the extension, e.g. `fonts/inter-latin.woff2`. */
  file: string
  style: string
  /** May be a variable range such as `400 700`. */
  weight: string
  /** Only on families with a `wdth` axis, e.g. `100%`. */
  stretch?: string
  unicodeRange: string
}

export interface FontOption {
  id: string
  label: string
  /** `bundled` fonts ship as woff2; `system` fonts rely on the user's OS. */
  source: 'bundled' | 'system'
  kind: 'sans' | 'mono'
  /** Full CSS font-family stack, Latin first then Japanese fallbacks. */
  stack: string
  note?: string
}

export interface FontSettings {
  enabled: boolean
  /** Which products this feature applies to. */
  scope: Scope
  /** Id from FONT_OPTIONS (sans), or KEEP_FAMILY to leave the font alone. */
  family: string
  /** Also replace monospace elements (code, pre, kbd). */
  applyToMonospace: boolean
  /** Id from FONT_OPTIONS (mono). */
  monoFamily: string
  /** Adds -webkit-font-smoothing: antialiased. */
  smoothing: boolean
  /** Multiplier for every declared font-size. 1 = unchanged. */
  sizeScale: number
  /** Floor in px applied after scaling. 0 = off. */
  minSize: number
  /** Added to every declared font-weight, clamped to 900. 0 = off. */
  weightBump: number
}

/**
 * Which products a feature acts on. One Cybozu host serves several, so this is
 * decided per page from the URL path — see src/shared/scope.ts. Each feature
 * carries its own scope.
 */
export interface Scope {
  /** `/k/…` */
  kintone: boolean
  /** `/g/…` */
  garoon: boolean
  /** Everything else on the host: portal, login, cybozu.com admin. */
  other: boolean
}

export interface GithubSettings {
  enabled: boolean
}

export interface ScheduleSettings {
  enabled: boolean
  /** How many days to show, starting today. */
  days: number
  /** Whether the floating card is rolled up to its pill. */
  collapsed: boolean
}

/**
 * Branch-lock windows published on a Garoon group calendar, surfaced on GitHub
 * pull requests so nobody merges into a closed branch.
 */
export interface BranchLockSettings {
  enabled: boolean
  /** e.g. https://example.cybozu.com — captured when you visit a Cybozu page. */
  origin: string
  /** Garoon organization id whose calendar carries the windows. */
  organizationId: string
  /** How far ahead to look, in days. */
  days: number
}

export interface Settings {
  font: FontSettings
  github: GithubSettings
  schedule: ScheduleSettings
  branchLock: BranchLockSettings
}
